### PR TITLE
Fix infinite loop whitelisting

### PR DESCRIPTION
**Pull request by valerybugakov**
While developing the other extensions which works with HTTP request interception, I frequently encounter the case when whitelist check goes into the infinite loop. 

This small PR resolves this issue.

### CODE REVIEW

**Comment by kzar** [comment]
I'm not sure that this code is working like you expect. The `frame` Object is usually (always?) provided by `ext/background.js`, where we carefully keep track of pages and frames. When storing the parent frame, [we use the `parentFrameId` property of the request event](https://github.com/adblockplus/adblockpluschrome/blob/729d07a/ext/background.js#L164-L166). [Looking at the documentation](https://developer.chrome.com/extensions/webRequest), this is set to -1 when no parent frame exists - in other words for top-level frames.

Perhaps you're confusing this with `window.parent`, which is equal to `window` for top-level frames? Or perhaps I'm misunderstanding?

Either way, thanks for taking the time to submit a pull request.

**Comment by valerybugakov** [comment]
@kzar I use `Network.requestIntercepted` API in the extension and somehow `frame` with id -1 got set into the `framesMap`. Which leads to the infinite loop in whitelist check, because that `frame` has an `id === -1` and `parentId === -1`. Change in this PR solves the problem for such an extension. I've tested it locally in different versions of Chrome.

**Comment by kzar** [comment]
> @kzar I use Network.requestIntercepted API in the extension and somehow frame with id -1 got set into the framesMap.

I don't see `Network.requestIntercepted` nor `framesMap` in the extension code, I checked the adblockpluschrome, adblockpluscore and adblockplusui repositories. Please could you clarify?

> Which leads to the infinite loop in whitelist check, because that frame has an id === -1 and parentId === -1.

I have never witnessed this symptom in Adblock Plus, please could you provide some concrete steps for me to reproduce?

> Change in this PR solves the problem for such an extension. I've tested it locally in different versions of Chrome.

For which extension did adding this check help? Which versions of Chrome did you test with?

**Comment by kzar** [comment]
@fhd Please could you close this one for me?

**Comment by fhd** [comment]
@kzar Done, also gave you the rights to do that yourself in the future while at it :smile:

**Pull request closed without merging**
